// FirstCampus3F.js - Milestone M0: First Campus 3F Doctor Administrative Area & Room 316
import * as THREE from 'three';
import { gameState } from '../../core/GameState.js';
import { Level3FBlockout } from '../Level3FBlockout.js';
import { disposeZoneArt } from '../../art/ArtResources.js';
import { applyFirstFloorArt } from '../../art/FirstFloorArt.js';
import { applyAct1CollisionHotfix } from '../CollisionHotfix.js';
import { KeyedKnobDoor } from '../shared/KeyedKnobDoor.js';
import { asset, solid } from '../../art/ArtDetails.js';

export class FirstCampus3F {
  constructor(scene, geometryFactory) {
    this.scene = scene;
    this.geometryFactory = geometryFactory;
    this.gf = geometryFactory;
    this.colliders = [];
    this.walkables = [];
    this.interactables = [];
    this.zoneGroup = new THREE.Group();
    this.zoneGroup.name = 'FirstCampus3F_Zone';
    this.levelInstance = null;
  }

  build() {
    this.scene.add(this.zoneGroup);
    // Pass zoneGroup so all meshes, lights, signs are children of zoneGroup, not global scene
    this.levelInstance = new Level3FBlockout(this.zoneGroup);
    applyAct1CollisionHotfix(this.levelInstance);
    applyFirstFloorArt(this.levelInstance);

    this.colliders = this.levelInstance.colliders;
    this.walkables = this.levelInstance.walkables;
    this.interactables = this.levelInstance.interactables;

    // Bespoke east archive wing: avoids the stray partition generated by the generic room-wing shell.
    const m=this.gf.materials;
    this.accessDoors={};this.keyedDoors={};

    // 3F office mirrors the 4F duty-room position relative to the shared elevator core.
    // 4F duty room bounds [-14,2,-8,10] relative to core origin [0,6] become
    // 3F office bounds [-22,3.5,-16,11.5] relative to core origin [-8,7.5].
    this.gf.buildFloor(this.zoneGroup,this.walkables,-19,0,7.5,6,8,m.floorWood);
    this.gf.buildCeiling(this.zoneGroup,-19,3.2,7.5,6,8);
    this.gf.buildWall(this.zoneGroup,this.colliders,-22,1.6,7.5,.22,3.2,8);
    this.gf.buildWall(this.zoneGroup,this.colliders,-19,1.6,3.5,6,3.2,.22);
    this.gf.buildWall(this.zoneGroup,this.colliders,-19,1.6,11.5,6,3.2,.22);
    this.gf.buildCeilingLight(this.zoneGroup,-19,3.15,7.5,.72,7);

    const adminDeskSurface=.82;
    const officeDeskTop=solid(this.zoneGroup,m.floorWood,[-19.25,.78,5.35],[2.25,.08,.85]);
    officeDeskTop.name='AdminDesk_Surface';
    solid(this.zoneGroup,m.metal,[-20.10,.38,5.35],[.08,.72,.08]);
    solid(this.zoneGroup,m.metal,[-18.40,.38,5.35],[.08,.72,.08]);
    asset(this.zoneGroup,'officeChair',[-19.25,0,6.35],[1,1,1],Math.PI);
    asset(this.zoneGroup,'storageCabinet',[-21.35,0,10.55],[.88,.88,.88],Math.PI/2);
    asset(this.zoneGroup,'storageCabinet',[-20.15,0,10.55],[.88,.88,.88],Math.PI/2);
    asset(this.zoneGroup,'officeChair',[-18.05,0,6.30],[.92,.92,.92],Math.PI);
    asset(this.zoneGroup,'officeChair',[-17.25,0,6.30],[.92,.92,.92],Math.PI);

    // Grounded desk props: every object's physical bottom is snapped to the desk surface.
    const adminPrinter=solid(this.zoneGroup,m.wall,[-20.28,adminDeskSurface+.14,5.30],[.50,.28,.38]);
    adminPrinter.name='AdminDesk_Printer';
    const printerTop=solid(this.zoneGroup,m.wallDark,[-20.28,adminDeskSurface+.295,5.27],[.38,.03,.26]);
    printerTop.name='AdminDesk_PrinterTop';
    const printerPaper=solid(this.zoneGroup,m.lightWarm,[-20.28,adminDeskSurface+.318,5.22],[.28,.012,.20]);
    printerPaper.name='AdminDesk_PrinterPaper';

    const monitorBase=solid(this.zoneGroup,m.metal,[-19.25,adminDeskSurface+.015,5.18],[.34,.03,.22]);
    monitorBase.name='AdminDesk_MonitorBase';
    const monitorStem=solid(this.zoneGroup,m.metal,[-19.25,adminDeskSurface+.18,5.18],[.06,.33,.06]);
    monitorStem.name='AdminDesk_MonitorStem';
    const monitorScreen=solid(this.zoneGroup,m.wallDark,[-19.25,adminDeskSurface+.47,5.18],[.72,.44,.06]);
    monitorScreen.name='AdminDesk_Monitor';
    const adminKeyboard=solid(this.zoneGroup,m.wall,[-19.25,adminDeskSurface+.013,5.55],[.66,.026,.22]);
    adminKeyboard.name='AdminDesk_Keyboard';
    for(const [i,[x,z]] of [[0,[-18.45,5.25]],[1,[-18.20,5.25]],[2,[-17.95,5.25]]]){
      const file=solid(this.zoneGroup,m.lightWarm,[x,adminDeskSurface+.018,z],[.18,.036,.26]);
      file.name=`AdminDesk_File_${i}`;
    }

    // Under-desk pedestal for the secretary memo.
    const adminPedestal=solid(this.zoneGroup,m.wall,[-18.45,.35,5.55],[.52,.70,.58]);
    adminPedestal.name='AdminDesk_Pedestal';
    for(const y of [.20,.38,.56]){
      const front=solid(this.zoneGroup,m.wallDark,[-18.45,y,5.245],[.42,.12,.025]);
      front.name=`AdminDesk_DrawerFront_${y.toFixed(2)}`;
    }

    // Closed but unlocked office door on the shared-core side.
    this.adminOfficeDoor=new KeyedKnobDoor(this,{
      id:'3F_ADMIN_OFFICE_DOOR',x:-16,z:7.5,yaw:Math.PI/2,width:1.35,title:'3F 行政辦公室'
    });
    this.adminOfficeDoor.setClosed(true);
    this.adminOfficeDoor.interactionData.label='3F 行政辦公室｜開門';

    // Physician roster is moved inside this office, where it becomes an optional investigation task.
    const rosterCanvas=document.createElement('canvas');rosterCanvas.width=1200;rosterCanvas.height=520;
    const rctx=rosterCanvas.getContext('2d');
    rctx.fillStyle='#e9ece7';rctx.fillRect(0,0,1200,520);
    rctx.fillStyle='#344d40';rctx.fillRect(0,0,1200,78);
    rctx.fillStyle='#fff';rctx.font='bold 34px sans-serif';rctx.fillText('青嶺醫療中心｜夜間醫師值勤名冊',28,51);
    const staff=[['林醫師','總醫師'],['周醫師','住院醫師'],['陳醫師','住院醫師'],['許醫師','主治醫師'],['江醫師','主治醫師'],['方醫師','值班支援']];
    staff.forEach(([name,role],i)=>{
      const col=i%3,row=Math.floor(i/3),x=38+col*385,y=112+row*190;
      rctx.fillStyle='#c9d1ca';rctx.beginPath();rctx.arc(x+58,y+56,42,0,Math.PI*2);rctx.fill();
      rctx.fillStyle='#6f7c74';rctx.beginPath();rctx.arc(x+58,y+47,17,0,Math.PI*2);rctx.fill();rctx.fillRect(x+35,y+67,46,25);
      rctx.fillStyle='#26372f';rctx.font='bold 27px sans-serif';rctx.fillText(name,x+118,y+48);
      rctx.font='21px sans-serif';rctx.fillStyle='#657168';rctx.fillText(role,x+118,y+83);
      rctx.strokeStyle='#b7beb8';rctx.strokeRect(x,y,340,135);
    });
    const rosterTex=new THREE.CanvasTexture(rosterCanvas);rosterTex.colorSpace=THREE.SRGBColorSpace;
    const rosterFace=new THREE.Mesh(new THREE.PlaneGeometry(2.65,1.15),new THREE.MeshStandardMaterial({map:rosterTex,roughness:.9}));
    rosterFace.position.set(-19,1.92,11.365);rosterFace.rotation.y=Math.PI;
    rosterFace.userData={interactable:true,id:'3F_ADMIN_ROSTER_TASK',type:'admin_roster_3f',label:'核對夜間醫師值勤名冊'};
    this.zoneGroup.add(rosterFace);this.interactables.push(rosterFace);

    // A loose, faded photocopy is the reward for checking the roster: suggestive, not explanatory.
    const oldSheet=solid(this.zoneGroup,m.lightWarm,[-18.55,.845,5.53],[.34,.018,.25]);
    oldSheet.rotation.y=-.14;oldSheet.userData={decorative:true,clue:'old_roster_lee_316'};
    this.adminRosterTask={id:'3F_ADMIN_ROSTER_TASK',optional:true,reward:'OLD_ROSTER_LEE_316',room:'3F_CORE_OFFICE'};

    const officeSignCanvas=document.createElement('canvas');officeSignCanvas.width=720;officeSignCanvas.height=200;
    const osctx=officeSignCanvas.getContext('2d');
    osctx.fillStyle='#edf2ee';osctx.fillRect(0,0,720,200);osctx.fillStyle='#24513a';osctx.fillRect(0,0,720,48);
    osctx.fillStyle='#173127';osctx.font='bold 38px sans-serif';osctx.fillText('3F 行政辦公室',34,125);
    osctx.font='20px sans-serif';osctx.fillStyle='#607168';osctx.fillText('ADMINISTRATIVE OFFICE',36,164);
    const officeSignTex=new THREE.CanvasTexture(officeSignCanvas);officeSignTex.colorSpace=THREE.SRGBColorSpace;
    const officeSign=new THREE.Mesh(new THREE.PlaneGeometry(1.55,.43),new THREE.MeshBasicMaterial({map:officeSignTex}));
    officeSign.position.set(-15.885,2.45,6.05);officeSign.rotation.y=Math.PI/2;this.zoneGroup.add(officeSign);
    this.coreOffice3F={
      id:'3F_CORE_OFFICE',label:'3F 行政辦公室',
      bounds:[-22,3.5,-16,11.5],door:[-16,1.7,7.5],doorId:'3F_ADMIN_OFFICE_DOOR',
      taskId:'3F_ADMIN_ROSTER_TASK',relativeTo4FDutyRoom:true,coreOrigin:[-8,7.5]
    };
    this.gf.buildFloor(this.zoneGroup,this.walkables,20,0,0,8,3.6,m.floor);
    this.gf.buildCeiling(this.zoneGroup,20,3.2,0,8,3.6);
    this.gf.buildWall(this.zoneGroup,this.colliders,20,1.6,1.8,8,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,24,1.6,0,.2,3.2,3.6);
    this.gf.buildWall(this.zoneGroup,this.colliders,17.1,1.6,-1.8,2.2,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,21.9,1.6,-1.8,4.2,3.2,.2);
    this.gf.buildCeilingLight(this.zoneGroup,20,3.15,0,.7,6);

    this.gf.buildFloor(this.zoneGroup,this.walkables,20,0,-4.5,7.4,5.4,m.floor);
    this.gf.buildCeiling(this.zoneGroup,20,3.2,-4.5,7.4,5.4);
    this.gf.buildWall(this.zoneGroup,this.colliders,20,1.6,-7.2,7.4,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,16.3,1.6,-4.5,.2,3.2,5.4);
    this.gf.buildWall(this.zoneGroup,this.colliders,23.7,1.6,-4.5,.2,3.2,5.4);
    this.gf.buildCeilingLight(this.zoneGroup,20,3.15,-4.5,.7,6);

    this.accessDoors??={};this.keyedDoors??={};
    this.archiveDoor=new KeyedKnobDoor(this,{id:'3F_ARCHIVE_DOOR',x:19,z:-1.8,width:1.6,title:'無門牌房間'});
    this.archiveDoor.setClosed(true);

    // Night guard patrol checkpoint opposite the museum wall. The 316 spare key is hidden here.
    const patrolBox=solid(this.zoneGroup,m.metal,[19,1.34,1.69],[.48,.62,.12]);
    patrolBox.name='GuardPatrolCheckpoint_3F';
    const patrolCanvas=document.createElement('canvas');patrolCanvas.width=480;patrolCanvas.height=220;
    const pctx=patrolCanvas.getContext('2d');pctx.fillStyle='#dfe5e0';pctx.fillRect(0,0,480,220);
    pctx.fillStyle='#385344';pctx.fillRect(0,0,480,58);pctx.fillStyle='#fff';pctx.font='bold 25px sans-serif';pctx.fillText('夜間警衛查哨點',20,39);
    pctx.fillStyle='#34463d';pctx.font='20px sans-serif';pctx.fillText('巡檢紀錄／備援物品',20,96);pctx.fillText('17:00  三樓交接巡查',20,132);pctx.fillText('STAFF ONLY',20,172);
    const patrolTex=new THREE.CanvasTexture(patrolCanvas);patrolTex.colorSpace=THREE.SRGBColorSpace;
    this.patrolCanvas=patrolCanvas;this.patrolContext=pctx;this.patrolTexture=patrolTex;
    const patrolFace=new THREE.Mesh(new THREE.PlaneGeometry(.42,.38),new THREE.MeshBasicMaterial({map:patrolTex}));
    patrolFace.position.set(19,1.38,1.625);patrolFace.rotation.y=Math.PI;this.zoneGroup.add(patrolFace);
    const hiddenKey=new THREE.Mesh(new THREE.TorusGeometry(.045,.009,10,20),m.stainless);hiddenKey.visible=false;hiddenKey.position.set(19,1.18,1.61);this.zoneGroup.add(hiddenKey);
    const patrolHit=new THREE.Mesh(new THREE.BoxGeometry(.70,.80,.24),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));
    patrolHit.position.set(19,1.34,1.62);
    patrolHit.userData={interactable:true,id:'316_SPARE_KEY',type:'spare_key_316',label:'檢查夜間警衛查哨點',targetGroup:hiddenKey};
    this.zoneGroup.add(patrolHit);this.interactables.push(patrolHit);this.spareKeyMesh=patrolHit;
    this.guardPatrolPoint={id:'3F_GUARD_PATROL_POINT',position:[19,1.34,1.69],opposite:'3F_ARCHIVE_DOOR'};

    const shelfMat=this.gf.materials.floorWood,folderMat=this.gf.materials.doorWood;
    const buildShelf=(id,x,z,yaw=0)=>{
      const g=new THREE.Group();g.name=`ArchiveShelf_${id}`;g.position.set(x,0,z);g.rotation.y=yaw;this.zoneGroup.add(g);
      solid(g,shelfMat,[-.72,1.12,0],[.10,2.24,.38]);solid(g,shelfMat,[.72,1.12,0],[.10,2.24,.38]);
      solid(g,shelfMat,[0,1.12,-.17],[1.54,2.24,.05]);
      for(const y of [.12,.58,1.04,1.50,1.96])solid(g,shelfMat,[0,y,0],[1.54,.08,.42]);
      for(let row=0;row<4;row++)for(let col=0;col<7;col++){
        const mat=(row+col)%3===0?this.gf.materials.wallBumper:(row+col)%3===1?folderMat:this.gf.materials.wallDark;
        solid(g,mat,[-.55+col*.18,.34+row*.46,.07],[.14,.34,.22]);
      }
      g.updateWorldMatrix(true,true);this.colliders.push(new THREE.Box3().setFromObject(g));return g;
    };
    const shelves=[
      buildShelf('W1',16.78,-3.35,Math.PI/2),
      buildShelf('W2',16.78,-5.55,Math.PI/2),
      buildShelf('E1',23.22,-3.35,-Math.PI/2),
      buildShelf('E2',23.22,-5.55,-Math.PI/2)
    ];

    const documents=[
      {
        id:'ARCHIVE_NIGHT_RECORD',shelf:shelves[0],x:.26,y:1.66,
        title:'夜間值勤異常紀錄｜2001–2004',
        pages:[
          '【院內機密】夜間值勤異常紀錄彙整。\n\n多起紀錄提到凌晨 02:10–02:30 間，舊行政區電話曾收到沒有分機來源的內線。工程單位檢查後未發現線路故障。',
          '值勤紀錄 2002/11：\n「查房回程時，3F 安全梯門已自行關閉。門禁紀錄沒有刷卡資料。」\n\n值班人員於備註欄手寫：不要單獨確認第二次聲響。',
          '2004 年後同類紀錄停止列入正式交班，改以「設備異常」歸檔。\n\n頁尾蓋章：資料保密・禁止外洩。'
        ]
      },
      {
        id:'ARCHIVE_BUILDING_NOTE',shelf:shelves[1],x:-.18,y:1.20,
        title:'舊院區工程圖附註｜缺頁',
        pages:[
          '【本院專屬】工程圖冊索引顯示本冊原有 48 頁，目前僅存 41 頁。缺頁範圍集中於舊三樓與地下連通空間。',
          '手寫附註：\n「實際牆體位置與竣工圖不符。西側封閉空間深度多出約 2.4 公尺。」\n\n旁註日期已模糊。',
          '後續勘查申請被劃線取消。取消原因欄僅寫：\n「維持現況，不再開啟。」'
        ]
      },
      {
        id:'ARCHIVE_PHOTO_ENVELOPE',shelf:shelves[2],x:.08,y:.74,
        title:'未編目照片袋｜夜間巡視',
        pages:[
          '牛皮紙袋外側只寫著「3F／夜間」。沒有拍攝者姓名。',
          '第一張照片：空的電梯前廳，時鐘顯示 02:17。遠端安全梯門似乎半開。\n\n照片背面寫著：「門當時是鎖著的。」',
          '最後一張照片只拍到文件保管室門牌。照片邊緣有一行鉛筆字：\n「第一次看到它時，這裡沒有這個房間。」'
        ]
      },
      {
        id:'ARCHIVE_UNINDEXED_HANDOFF',shelf:shelves[3],x:-.26,y:1.66,
        title:'未編目交班紀錄｜無年份',
        pages:[
          '封面沒有日期，也沒有歸檔編號。第一頁只有一句話：\n\n「如果你是從 316 的系統訊息找到這裡，代表它又開始了。」',
          '第二頁列出幾個重複時間：02:17、03:16、04:09。旁邊有人用紅筆寫：\n\n「不要把它當成樓層或房號。」',
          '最後一頁只剩一行：\n\n「今晚先完成值班。真正要找的東西，不在病歷裡。」\n\n頁角蓋著模糊的舊院章。\n\n旁邊夾著一張殘缺索引：409／舊隔離零號房；316／夜間封鎖決策點；1F／舊警衛台後配電；2F／舊式手圈索引。'
        ]
      }
    ];
    for(const d of documents){
      const folder=solid(d.shelf,this.gf.materials.lightWarm,[d.x,d.y,.25],[.28,.36,.05]);
      folder.name=d.id;folder.userData={interactable:true,id:d.id,type:'archive_document',label:`翻閱：${d.title}`,documentTitle:d.title,pages:d.pages};
      this.interactables.push(folder);
    }

    const lore=document.createElement('canvas');lore.width=760;lore.height=300;const ctx=lore.getContext('2d');
    ctx.fillStyle='#d8d0bc';ctx.fillRect(0,0,760,300);ctx.fillStyle='#4a2f28';ctx.font='bold 34px sans-serif';ctx.fillText('文史館｜封存索引',28,50);
    ctx.font='23px sans-serif';ctx.fillStyle='#302b27';['資料保密・禁止外洩','工程紀錄／夜間紀錄／照片封存','調閱後請依原位置歸檔'].forEach((t,i)=>ctx.fillText('• '+t,42,112+i*55));
    const tex=new THREE.CanvasTexture(lore);tex.colorSpace=THREE.SRGBColorSpace;
    const board=new THREE.Mesh(new THREE.PlaneGeometry(2.8,1.05),new THREE.MeshStandardMaterial({map:tex,roughness:.95}));board.position.set(20,1.62,-7.08);this.zoneGroup.add(board);
    this.secretArchive={id:'3F_ARCHIVE',label:'文史館・封存資料室',doorId:'3F_ARCHIVE_DOOR',requires:'ARCHIVE_ACCESS_KEY',bookshelfCount:4,documentIds:documents.map(d=>d.id),lore:['night_anomaly_records','missing_floorplans','unlabelled_photos','unindexed_handoff']};

    // Two optional secrets inside 316. They are discoverable but not required for the duty workflow.
    const officeSecrets=[
      {
        id:'316_DRAWER_NOTE',position:[7.08,.62,6.55],size:[.34,.05,.24],title:'316 抽屜內的便條',
        pages:[
          '一張被壓在抽屜最底層的便條。\n\n「如果半夜內線響兩次，不要立刻回撥。先看值班本最後一頁。」',
          '背面只寫了三個數字：\n\n02:17\n\n筆跡和今晚值班本上的任何人都不同。'
        ]
      },
      {
        id:'316_OLD_SHIFT_MEMO',position:[7.35,2.02,8.18],size:[.42,.52,.03],title:'舊值班備忘錄',
        pages:[
          '舊版值班備忘錄，日期被撕掉。\n\n「三樓文件保管室非必要勿於深夜單獨進入。」',
          '最後一行被紅筆圈起：\n\n「看到不在平面圖上的門，先記錄位置，不要開。」'
        ]
      }
    ];
    for(const s of officeSecrets){
      const paper=solid(this.zoneGroup,m.lightWarm,s.position,s.size);
      paper.name=s.id;paper.userData={interactable:true,id:s.id,type:'archive_document',label:`翻閱：${s.title}`,documentTitle:s.title,pages:s.pages};
      this.interactables.push(paper);
    }
    this.officeSecrets={count:officeSecrets.length,ids:officeSecrets.map(s=>s.id)};

    // References for gameplay state
    this.keyMesh = this.levelInstance.keyMesh;
    this.workstationMesh = this.levelInstance.workstationMesh;
    this.dutyLogMesh = this.levelInstance.dutyLogMesh;
    this.elevatorLight = this.levelInstance.elevatorLight;
    this.explorationArea = this.levelInstance.explorationArea;
    this.keyMesh.visible = false;
    this.keyMesh.userData.targetGroup.visible = false;
    this.keyMesh.userData.interactable = false;
    this.lockerMesh = this.levelInstance.lockerMesh;
    if(gameState.getFlag('FOUND_316_SPARE_KEY')){
      this.spareKeyMesh.userData.interactable=false;
      if(this.spareKeyMesh.userData.targetGroup)this.spareKeyMesh.userData.targetGroup.visible=false;
    }
    if(gameState.getFlag('OPENED_316'))this.levelInstance.open316Door();
    if(gameState.getFlag('LOCKER_OPENED'))this.levelInstance.markLockerOpen();
    if(gameState.getFlag('OFFICE_302_UNLOCKED'))this.levelInstance.unlock302();
    if(gameState.getFlag('ARCHIVE_ACCESS_KEY')){
      if(this.levelInstance.museumKey302){
        this.levelInstance.museumKey302.userData.interactable=false;
        if(this.levelInstance.museumKey302.userData.targetGroup)this.levelInstance.museumKey302.userData.targetGroup.visible=false;
      }
    }
    const savedAnne=Number(gameState.getFlag('ANNE_STAGE')||0);
    if(savedAnne>0)this.levelInstance.setAnneStage(savedAnne);
    if(gameState.getFlag('GUARD_FUTURE_ENTRY'))this.setPatrolFutureEntry();
    this.updateElevatorLight(gameState.areRequiredTasksComplete());

    // Phase-driven environmental layers are authored once and toggled by applyGamePhase().
    this.phaseRedLight=new THREE.PointLight(0x7a1616,0,14,2);
    this.phaseRedLight.position.set(6,2.55,0);this.zoneGroup.add(this.phaseRedLight);
    this.phaseWetMarks=new THREE.Group();this.phaseWetMarks.name='Phase3_2117_WetFootprints';this.phaseWetMarks.visible=false;this.zoneGroup.add(this.phaseWetMarks);
    const wetMat=new THREE.MeshStandardMaterial({color:0x272b2a,transparent:true,opacity:.28,roughness:.25});
    [[18.6,1.2],[17.8,.8],[17.0,.45],[16.2,.10]].forEach(([x,z],i)=>{
      for(const dz of [-.10,.10]){
        const mark=new THREE.Mesh(new THREE.PlaneGeometry(.16,.32),wetMat);
        mark.rotation.x=-Math.PI/2;mark.rotation.z=(i%2?.14:-.12);mark.position.set(x,.012,z+dz);this.phaseWetMarks.add(mark);
      }
    });
    this.applyGamePhase(gameState.getGamePhase?.()||'Phase0_1700_FirstArrival');

    return this;
  }

  applyGamePhase(phase,state=gameState) {
    this.currentGamePhase=phase;
    if(this.phaseRedLight)this.phaseRedLight.intensity=0;
    if(this.phaseWetMarks)this.phaseWetMarks.visible=false;

    if(phase==='Phase0_1700_FirstArrival'){
      return;
    }

    if(phase==='Phase1_1715_AfterArchive'){
      if(Number(state.getFlag('ANNE_STAGE')||0)<2)state.setFlag('ANNE_STAGE',2);
      return;
    }

    if(phase==='Phase2_2040_ElevatorGlitch'){
      this.phaseRedLight.intensity=2.6;
      state.setFlag('ANNE_STAGE',3);
      this.levelInstance?.setAnneStage?.(3);
      return;
    }

    if(phase==='Phase3_2117_NightPatrol'){
      this.phaseRedLight.intensity=.55;
      if(this.phaseWetMarks)this.phaseWetMarks.visible=true;
      this.setPatrolFutureEntry();
    }
  }

  open316Door() {
    return this.levelInstance?.open316Door?.() || false;
  }

  markLockerOpen() {
    this.levelInstance?.markLockerOpen?.();
  }

  unlock302() {
    return this.levelInstance?.unlock302?.() || false;
  }

  setPatrolFutureEntry() {
    if(!this.patrolContext||!this.patrolCanvas||!this.patrolTexture)return;
    const ctx=this.patrolContext,canvas=this.patrolCanvas;
    ctx.fillStyle='#dfe5e0';ctx.fillRect(0,0,canvas.width,canvas.height);
    ctx.fillStyle='#385344';ctx.fillRect(0,0,canvas.width,58);ctx.fillStyle='#fff';ctx.font='bold 25px sans-serif';ctx.fillText('夜間警衛查哨點',20,39);
    ctx.fillStyle='#34463d';ctx.font='20px sans-serif';ctx.fillText('巡檢紀錄／備援物品',20,94);ctx.fillText('17:00  三樓交接巡查',20,128);
    ctx.fillStyle='#8a2f29';ctx.font='bold 21px sans-serif';ctx.fillText('21:17  三樓巡查完成',20,164);
    ctx.fillStyle='#34463d';ctx.font='16px sans-serif';ctx.fillText('STAFF ONLY',20,198);
    this.patrolTexture.needsUpdate=true;
  }

  syncHorrorState() {
    if(gameState.getFlag('GUARD_FUTURE_ENTRY'))this.setPatrolFutureEntry();
  }

  isAnneObject(obj) {
    const anne=this.levelInstance?.anneGroup;
    for(let p=obj;p;p=p.parent)if(p===anne)return true;
    return false;
  }

  isAnneVisibleToPlayer(camera) {
    const anne=this.levelInstance?.anneGroup;
    if(!anne)return false;
    camera.updateMatrixWorld(true);
    anne.updateWorldMatrix(true,true);

    const vp=new THREE.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse);
    const frustum=new THREE.Frustum().setFromProjectionMatrix(vp);
    const bounds=new THREE.Box3().setFromObject(anne);
    if(!frustum.intersectsBox(bounds))return false;

    const cameraPos=new THREE.Vector3();camera.getWorldPosition(cameraPos);
    const targets=[bounds.getCenter(new THREE.Vector3())];
    if(this.levelInstance.anneHead){
      const headPos=new THREE.Vector3();this.levelInstance.anneHead.getWorldPosition(headPos);targets.push(headPos);
    }

    this._anneRaycaster??=new THREE.Raycaster();
    for(const target of targets){
      const delta=target.clone().sub(cameraPos),distance=delta.length();
      if(distance<.001)continue;
      this._anneRaycaster.set(cameraPos,delta.normalize());
      this._anneRaycaster.far=distance-.04;
      const hits=this._anneRaycaster.intersectObjects(this.scene.children,true);
      const blocker=hits.find(hit=>{
        if(this.isAnneObject(hit.object))return false;
        const mat=hit.object?.material;
        if(mat?.transparent&&Number(mat.opacity)<=.08)return false;
        if(hit.object?.visible===false)return false;
        return true;
      });
      if(!blocker)return true;
    }
    return false;
  }

  update(camera) {
    if(!camera||!this.levelInstance?.anneGroup)return;
    const desired=Number(gameState.getFlag('ANNE_STAGE')||0);
    if(desired<=this.levelInstance.anneStage)return;
    if(!this.isAnneVisibleToPlayer(camera))this.levelInstance.setAnneStage(desired);
  }

  updateElevatorLight(isReady) {
    if (this.levelInstance) {
      this.levelInstance.updateElevatorLight(isReady);
    }
  }

  cleanup() {
    if (this.zoneGroup) {
      this.scene.remove(this.zoneGroup);
      disposeZoneArt(this.zoneGroup);
    }
    this.levelInstance = null;
    this.colliders = [];
    this.walkables = [];
    this.interactables = [];
  }
}
