// FirstCampus3F.js - Milestone M0: First Campus 3F Doctor Administrative Area & Room 316
import * as THREE from 'three';
import { gameState } from '../../core/GameState.js';
import { Level3FBlockout } from '../Level3FBlockout.js';
import { disposeZoneArt } from '../../art/ArtResources.js';
import { applyFirstFloorArt } from '../../art/FirstFloorArt.js';
import { applyAct1CollisionHotfix } from '../CollisionHotfix.js';
import { KeyedKnobDoor } from '../shared/KeyedKnobDoor.js';
import { asset, solid } from '../../art/ArtDetails.js';

export class FirstCampus3F {
  constructor(scene, geometryFactory) {
    this.scene = scene;
    this.geometryFactory = geometryFactory;
    this.gf = geometryFactory;
    this.colliders = [];
    this.walkables = [];
    this.interactables = [];
    this.zoneGroup = new THREE.Group();
    this.zoneGroup.name = 'FirstCampus3F_Zone';
    this.levelInstance = null;
  }

  build() {
    this.scene.add(this.zoneGroup);
    // Pass zoneGroup so all meshes, lights, signs are children of zoneGroup, not global scene
    this.levelInstance = new Level3FBlockout(this.zoneGroup);
    applyAct1CollisionHotfix(this.levelInstance);
    applyFirstFloorArt(this.levelInstance);

    this.colliders = this.levelInstance.colliders;
    this.walkables = this.levelInstance.walkables;
    this.interactables = this.levelInstance.interactables;

    // Bespoke east archive wing: avoids the stray partition generated by the generic room-wing shell.
    const m=this.gf.materials;
    this.gf.buildFloor(this.zoneGroup,this.walkables,20,0,0,8,3.6,m.floor);
    this.gf.buildCeiling(this.zoneGroup,20,3.2,0,8,3.6);
    this.gf.buildWall(this.zoneGroup,this.colliders,20,1.6,1.8,8,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,24,1.6,0,.2,3.2,3.6);
    this.gf.buildWall(this.zoneGroup,this.colliders,17.1,1.6,-1.8,2.2,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,21.9,1.6,-1.8,4.2,3.2,.2);
    this.gf.buildCeilingLight(this.zoneGroup,20,3.15,0,.7,6);

    this.gf.buildFloor(this.zoneGroup,this.walkables,20,0,-4.5,7.4,5.4,m.floor);
    this.gf.buildCeiling(this.zoneGroup,20,3.2,-4.5,7.4,5.4);
    this.gf.buildWall(this.zoneGroup,this.colliders,20,1.6,-7.2,7.4,3.2,.2);
    this.gf.buildWall(this.zoneGroup,this.colliders,16.3,1.6,-4.5,.2,3.2,5.4);
    this.gf.buildWall(this.zoneGroup,this.colliders,23.7,1.6,-4.5,.2,3.2,5.4);
    this.gf.buildCeilingLight(this.zoneGroup,20,3.15,-4.5,.7,6);

    this.accessDoors={};this.keyedDoors={};
    this.archiveDoor=new KeyedKnobDoor(this,{id:'3F_ARCHIVE_DOOR',x:19,z:-1.8,width:1.6,title:'文史館・封存資料室'});
    this.archiveDoor.setClosed(true);
    const shelfMat=this.gf.materials.floorWood,folderMat=this.gf.materials.doorWood;
    const buildShelf=(id,x,z,yaw=0)=>{
      const g=new THREE.Group();g.name=`ArchiveShelf_${id}`;g.position.set(x,0,z);g.rotation.y=yaw;this.zoneGroup.add(g);
      solid(g,shelfMat,[-.72,1.12,0],[.10,2.24,.38]);solid(g,shelfMat,[.72,1.12,0],[.10,2.24,.38]);
      solid(g,shelfMat,[0,1.12,-.17],[1.54,2.24,.05]);
      for(const y of [.12,.58,1.04,1.50,1.96])solid(g,shelfMat,[0,y,0],[1.54,.08,.42]);
      for(let row=0;row<4;row++)for(let col=0;col<7;col++){
        const mat=(row+col)%3===0?this.gf.materials.wallBumper:(row+col)%3===1?folderMat:this.gf.materials.wallDark;
        solid(g,mat,[-.55+col*.18,.34+row*.46,.07],[.14,.34,.22]);
      }
      g.updateWorldMatrix(true,true);this.colliders.push(new THREE.Box3().setFromObject(g));return g;
    };
    const shelves=[
      buildShelf('W1',16.78,-3.35,Math.PI/2),
      buildShelf('W2',16.78,-5.55,Math.PI/2),
      buildShelf('E1',23.22,-3.35,-Math.PI/2),
      buildShelf('E2',23.22,-5.55,-Math.PI/2)
    ];

    const documents=[
      {
        id:'ARCHIVE_NIGHT_RECORD',shelf:shelves[0],x:.26,y:1.66,
        title:'夜間值勤異常紀錄｜2001–2004',
        pages:[
          '【院內機密】夜間值勤異常紀錄彙整。\n\n多起紀錄提到凌晨 02:10–02:30 間，舊行政區電話曾收到沒有分機來源的內線。工程單位檢查後未發現線路故障。',
          '值勤紀錄 2002/11：\n「查房回程時，3F 安全梯門已自行關閉。門禁紀錄沒有刷卡資料。」\n\n值班人員於備註欄手寫：不要單獨確認第二次聲響。',
          '2004 年後同類紀錄停止列入正式交班，改以「設備異常」歸檔。\n\n頁尾蓋章：資料保密・禁止外洩。'
        ]
      },
      {
        id:'ARCHIVE_BUILDING_NOTE',shelf:shelves[1],x:-.18,y:1.20,
        title:'舊院區工程圖附註｜缺頁',
        pages:[
          '【本院專屬】工程圖冊索引顯示本冊原有 48 頁，目前僅存 41 頁。缺頁範圍集中於舊三樓與地下連通空間。',
          '手寫附註：\n「實際牆體位置與竣工圖不符。西側封閉空間深度多出約 2.4 公尺。」\n\n旁註日期已模糊。',
          '後續勘查申請被劃線取消。取消原因欄僅寫：\n「維持現況，不再開啟。」'
        ]
      },
      {
        id:'ARCHIVE_PHOTO_ENVELOPE',shelf:shelves[2],x:.08,y:.74,
        title:'未編目照片袋｜夜間巡視',
        pages:[
          '牛皮紙袋外側只寫著「3F／夜間」。沒有拍攝者姓名。',
          '第一張照片：空的電梯前廳，時鐘顯示 02:17。遠端安全梯門似乎半開。\n\n照片背面寫著：「門當時是鎖著的。」',
          '最後一張照片只拍到文件保管室門牌。照片邊緣有一行鉛筆字：\n「第一次看到它時，這裡沒有這個房間。」'
        ]
      },
      {
        id:'ARCHIVE_UNINDEXED_HANDOFF',shelf:shelves[3],x:-.26,y:1.66,
        title:'未編目交班紀錄｜無年份',
        pages:[
          '封面沒有日期，也沒有歸檔編號。第一頁只有一句話：\n\n「如果你是從 316 的系統訊息找到這裡，代表它又開始了。」',
          '第二頁列出幾個重複時間：02:17、03:16、04:09。旁邊有人用紅筆寫：\n\n「不要把它當成樓層或房號。」',
          '最後一頁只剩一行：\n\n「今晚先完成值班。真正要找的東西，不在病歷裡。」\n\n頁角蓋著模糊的舊院章。'
        ]
      }
    ];
    for(const d of documents){
      const folder=solid(d.shelf,this.gf.materials.lightWarm,[d.x,d.y,.25],[.28,.36,.05]);
      folder.name=d.id;folder.userData={interactable:true,id:d.id,type:'archive_document',label:`翻閱：${d.title}`,documentTitle:d.title,pages:d.pages};
      this.interactables.push(folder);
    }

    const lore=document.createElement('canvas');lore.width=760;lore.height=300;const ctx=lore.getContext('2d');
    ctx.fillStyle='#d8d0bc';ctx.fillRect(0,0,760,300);ctx.fillStyle='#4a2f28';ctx.font='bold 34px sans-serif';ctx.fillText('文史館｜封存索引',28,50);
    ctx.font='23px sans-serif';ctx.fillStyle='#302b27';['資料保密・禁止外洩','工程紀錄／夜間紀錄／照片封存','調閱後請依原位置歸檔'].forEach((t,i)=>ctx.fillText('• '+t,42,112+i*55));
    const tex=new THREE.CanvasTexture(lore);tex.colorSpace=THREE.SRGBColorSpace;
    const board=new THREE.Mesh(new THREE.PlaneGeometry(2.8,1.05),new THREE.MeshStandardMaterial({map:tex,roughness:.95}));board.position.set(20,1.62,-7.08);this.zoneGroup.add(board);
    this.secretArchive={id:'3F_ARCHIVE',label:'文史館・封存資料室',doorId:'3F_ARCHIVE_DOOR',requires:'STAFF_ACCESS_CARD',bookshelfCount:4,documentIds:documents.map(d=>d.id),lore:['night_anomaly_records','missing_floorplans','unlabelled_photos','unindexed_handoff']};

    // Two optional secrets inside 316. They are discoverable but not required for the duty workflow.
    const officeSecrets=[
      {
        id:'316_DRAWER_NOTE',position:[7.08,.62,6.55],size:[.34,.05,.24],title:'316 抽屜內的便條',
        pages:[
          '一張被壓在抽屜最底層的便條。\n\n「如果半夜內線響兩次，不要立刻回撥。先看值班本最後一頁。」',
          '背面只寫了三個數字：\n\n02:17\n\n筆跡和今晚值班本上的任何人都不同。'
        ]
      },
      {
        id:'316_OLD_SHIFT_MEMO',position:[7.35,2.02,8.18],size:[.42,.52,.03],title:'舊值班備忘錄',
        pages:[
          '舊版值班備忘錄，日期被撕掉。\n\n「三樓文件保管室非必要勿於深夜單獨進入。」',
          '最後一行被紅筆圈起：\n\n「看到不在平面圖上的門，先記錄位置，不要開。」'
        ]
      }
    ];
    for(const s of officeSecrets){
      const paper=solid(this.zoneGroup,m.lightWarm,s.position,s.size);
      paper.name=s.id;paper.userData={interactable:true,id:s.id,type:'archive_document',label:`翻閱：${s.title}`,documentTitle:s.title,pages:s.pages};
      this.interactables.push(paper);
    }
    this.officeSecrets={count:officeSecrets.length,ids:officeSecrets.map(s=>s.id)};

    // References for gameplay state
    this.keyMesh = this.levelInstance.keyMesh;
    this.workstationMesh = this.levelInstance.workstationMesh;
    this.dutyLogMesh = this.levelInstance.dutyLogMesh;
    this.elevatorLight = this.levelInstance.elevatorLight;
    this.explorationArea = this.levelInstance.explorationArea;
    this.keyMesh.visible = false;
    this.keyMesh.userData.targetGroup.visible = false;
    this.keyMesh.userData.interactable = false;
    this.spareKeyMesh = this.levelInstance.spareKeyMesh;
    this.lockerMesh = this.levelInstance.lockerMesh;
    if(gameState.getFlag('FOUND_316_SPARE_KEY')){
      this.spareKeyMesh.userData.interactable=false;
      if(this.spareKeyMesh.userData.targetGroup)this.spareKeyMesh.userData.targetGroup.visible=false;
    }
    if(gameState.getFlag('OPENED_316'))this.levelInstance.open316Door();
    if(gameState.getFlag('LOCKER_OPENED'))this.levelInstance.markLockerOpen();
    this.updateElevatorLight(gameState.areRequiredTasksComplete());

    return this;
  }

  open316Door() {
    return this.levelInstance?.open316Door?.() || false;
  }

  markLockerOpen() {
    this.levelInstance?.markLockerOpen?.();
  }

  updateElevatorLight(isReady) {
    if (this.levelInstance) {
      this.levelInstance.updateElevatorLight(isReady);
    }
  }

  cleanup() {
    if (this.zoneGroup) {
      this.scene.remove(this.zoneGroup);
      disposeZoneArt(this.zoneGroup);
    }
    this.levelInstance = null;
    this.colliders = [];
    this.walkables = [];
    this.interactables = [];
  }
}
