import assert from 'node:assert/strict';
import * as THREE from 'three';
import {WorldRouter} from './src/world/WorldRouter.js';
import {FPSController} from './src/player/FPSController.js';
global.document={querySelector:()=>null,addEventListener(){},createElement:()=>({getContext:()=>new Proxy({measureText:t=>({width:t.length*20})},{get:(o,k)=>o[k]||(()=>({addColorStop(){}}))})})};
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(),c=new FPSController(camera,{addEventListener(){}},[],[],[]),r=new WorldRouter(scene,camera,c);
let z=r.loadZone('first_campus_4f');const room=z.dutyRoom;
assert(room.bounds[2]<=-8);assert.equal(z.wardDoor.closed,true);assert.equal(z.dutyDoor.closed,true);
c.teleport(...room.outside);c.moveWithCollision(-3,0);assert(c.position.x>-8);
assert.equal(z.toggleDutyDoor(new THREE.Vector3(...room.outside)),true);
c.teleport(...room.outside);c.moveWithCollision(-3,0);assert(c.position.x<-9);
z.setDutyDoorClosed(true);r.loadZone('first_campus_3f');z=r.loadZone('first_campus_4f');assert(z.dutyDoor.closed);
assert.equal(z.dutyDoor.leaf.userData.type,'duty_door');
assert.match(z.dutyDoor.leaf.userData.label,/鑰匙/);
console.log('DUTY ROOM PASS: default closed keyed single-leaf knob door, traversal after unlock, closure/revisit persistence');
