import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const index=readFileSync('./index.html','utf8');
const main=readFileSync('./src/main.js','utf8');
const ui=readFileSync('./src/ui/UIManager.js','utf8');
const art=readFileSync('./src/art/FirstFloorArt.js','utf8');
const floor=readFileSync('./src/world/zones/FirstCampus3F.js','utf8');
const station=readFileSync('./src/world/shared/PlanArchitecture.js','utf8');
const door=readFileSync('./src/world/shared/AccessDoor.js','utf8');

assert(!index.includes('松德'),'Public game shell must not expose real-hospital name');
assert(index.includes('青嶺醫療中心'));
assert(index.includes('his-login-panel')&&index.includes('credential-slip'));
assert(index.includes('四位守門者')&&index.includes('17:00'),'Duty manual must carry the locker riddle');
assert(index.includes('locker-modal')&&index.includes('anomaly-modal'),'3F puzzle overlays missing');
assert(index.includes('HIS 帳號')&&index.includes('QL1700'),'Unlocked locker must reveal the night HIS credential card');
assert(!index.includes('虛構'),'Player-facing UI must not break immersion with fiction disclaimers');
assert(main.includes("!gameState.getFlag('STAFF_ACCESS_CARD')"),'Vertical travel must be card-gated');
assert(ui.includes('HIS_AUTHENTICATED'),'HIS must require duty credentials');
assert(ui.includes("p==='QL1700'"),'HIS password verifier must match the duty book');
assert(art.includes('夜間醫師值勤名冊'));
assert(floor.includes("title:'文史館・封存資料室'")&&floor.includes("requires:'STAFF_ACCESS_CARD'"));
assert(floor.includes("bookshelfCount:4")&&floor.includes("type:'archive_document'"));
assert(floor.includes("ARCHIVE_UNINDEXED_HANDOFF"),'Unindexed handoff clue missing');
assert(!floor.includes('buildRoomWing'),'Generic archive wing must not reintroduce the stray partition');
assert(floor.includes("officeSecrets={count:officeSecrets.length"),'316 secret exploration metadata missing');
const level=readFileSync('./src/world/Level3FBlockout.js','utf8');
assert(level.includes("◀ 電梯・逃生梯"),'Elevator and escape stair must point to the same side');
assert(level.includes("id:'3F_ELEVATOR_LOBBY'"),'Actual elevator-front exploration area missing');
assert(level.includes("type:'spare_key_316'"),'Hidden 316 spare key interaction missing');
assert(level.includes("type:'locker_316'"),'316 keypad locker missing');
assert(level.includes("type:'office_316_door'"),'Locked 316 office door missing');
assert(station.includes('alongX?sx:sx*.22+.025'),'Station side glazing must span its full axis');
assert(door.includes("mount:'jamb'")&&door.includes('mount.add(reader)'),'Readers must be physically parented to jamb mounts');
console.log('PRIVACY + 3F FAST QA PASS');
