import assert from 'node:assert/strict';
import * as THREE from 'three';
import {FirstCampus3F} from './src/world/zones/FirstCampus3F.js';
import {GeometryFactory} from './src/world/shared/GeometryFactory.js';
import {gameState} from './src/core/GameState.js';

global.document={createElement:()=>({getContext:()=>new Proxy({},{get:()=>()=>({addColorStop(){}})})})};
const scene=new THREE.Scene(),gf=new GeometryFactory();
gameState.setFlag('FOUND_316_SPARE_KEY',false);
let zone=new FirstCampus3F(scene,gf).build();
let key=zone.interactables.find(object=>object.userData.id==='316_SPARE_KEY');
assert(key,'316 spare-key checkpoint must exist');
assert.equal(key.userData.interactable,true,'Uncollected 316 spare key must be available');
gameState.setFlag('FOUND_316_SPARE_KEY',true);
gameState.markTaskComplete('FOUND_316_SPARE_KEY');
zone.cleanup();
zone=new FirstCampus3F(scene,gf).build();
key=zone.interactables.find(object=>object.userData.id==='316_SPARE_KEY');
assert.equal(key.userData.targetGroup.visible,false,'Collected 316 spare key must not reappear after zone return');
assert.equal(key.userData.interactable,false,'Collected 316 spare key must not offer pickup after zone return');
assert.equal(gameState.isTaskComplete('FOUND_316_SPARE_KEY'),true,'Cleanup must preserve spare-key task');
zone.cleanup();
console.log('316 SPARE KEY REVISIT PASS: checkpoint starts interactable; collected key stays hidden and unavailable after zone return');
