import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const index=readFileSync('./index.html','utf8');
const main=readFileSync('./src/main.js','utf8');
const ui=readFileSync('./src/ui/UIManager.js','utf8');
const art=readFileSync('./src/art/FirstFloorArt.js','utf8');
const floor=readFileSync('./src/world/zones/FirstCampus3F.js','utf8');
const station=readFileSync('./src/world/shared/PlanArchitecture.js','utf8');
const door=readFileSync('./src/world/shared/AccessDoor.js','utf8');
const level=readFileSync('./src/world/Level3FBlockout.js','utf8');
const verticalCore=readFileSync('./src/world/shared/VerticalCore.js','utf8');

assert(!index.includes('松德'),'Public game shell must not expose real-hospital name');
assert(index.includes('青嶺醫療中心'));
assert(index.includes('his-login-panel')&&index.includes('locker-modal')&&index.includes('riddle-slip'));
assert(index.includes('四位守門者')&&index.includes('17:00'),'Duty manual must carry the locker riddle');
assert(index.includes('locker-modal')&&index.includes('anomaly-modal'),'3F puzzle overlays missing');
assert(!index.includes('<b>HIS 帳號</b> night403'),'Keypad locker must not expose HIS credentials');
assert(level.includes("type:'credential_drawer_316'")&&level.includes('QL1700'),'HIS credentials must live in the under-desk drawer interaction');
assert(!index.includes('虛構'),'Player-facing UI must not break immersion with fiction disclaimers');
assert(main.includes("!gameState.getFlag('STAFF_ACCESS_CARD')"),'Vertical travel must be card-gated');
assert(ui.includes('HIS_AUTHENTICATED'),'HIS must require duty credentials');
assert(ui.includes("p==='QL1700'"),'HIS password verifier must match the duty book');
assert(art.includes('夜間醫師值勤名冊'));
assert(floor.includes("title:'無門牌房間'")&&floor.includes("requires:'ARCHIVE_ACCESS_KEY'"));
assert(floor.includes("bookshelfCount:4")&&floor.includes("type:'archive_document'"));
assert(floor.includes("ARCHIVE_UNINDEXED_HANDOFF"),'Unindexed handoff clue missing');
assert(!floor.includes('buildRoomWing'),'Generic archive wing must not reintroduce the stray partition');
assert(floor.includes("officeSecrets={count:officeSecrets.length"),'316 secret exploration metadata missing');
assert(level.includes("◀ 電梯・逃生梯"),'Elevator and escape stair must point to the same side');
assert(level.includes("id:'3F_ELEVATOR_LOBBY'"),'Actual elevator-front exploration area missing');
assert(floor.includes("type:'spare_key_316'")&&floor.includes('夜間警衛查哨點'),'316 spare key must be hidden at the guard patrol checkpoint opposite the museum');
assert(level.includes("type:'locker_316'"),'316 keypad locker missing');
assert(level.includes('316_HINT_1F_SECURITY')&&level.includes('316_HINT_1F_SERVICE')&&level.includes('316_HINT_OLD_ROUTE'),'316 hint shelf must seed 1F exploration clues');
assert(level.includes("type:'office_316_door'"),'Locked 316 office door missing');
assert(!level.includes('316_SPARE_KEY'),'316 spare key must not remain beside the office door');
assert(!main.includes('ContactShadows'),'3F floor-ring SSAO artifact path must be removed');
assert(!art.includes("box(-8.25,.47"),'Lobby benches must not sit in the 302/core doorway axes');
assert(art.includes("box(-6.35,1.72,-3.27"),'Lobby notice board must stay on the solid wall segment clear of 302');
assert(main.includes("ARCHIVE_ACCESS_KEY"),'Museum door must require the dedicated 4F key');
assert(main.includes("office_302_keypad")&&main.includes("museum_key_302"),'302 keypad/museum-key interactions missing');
assert(level.includes("code:'3082'")&&level.includes("MUSEUM_KEY_302"),'302 code puzzle or brass key missing');
assert(floor.includes("relativeTo4FDutyRoom:true")&&floor.includes("label:'3F 行政辦公室'"),'3F office matching the 4F duty-room relative position is missing');
assert(verticalCore.includes("zoneId==='first_campus_4f'||zoneId==='first_campus_3f'"),'3F shared elevator core must cut the west office doorway');
assert(level.includes("CPR_Anne")&&level.includes("type:'cpr_anne'"),'CPR Anne environmental-horror prop missing');
assert(main.includes("office_phone_316")&&main.includes("PHONE_ANSWERED"),'316 phone anomaly interaction missing');
assert(ui.includes("B1")&&ui.includes("B2"),'Post-archive elevator display glitch missing');
assert(station.includes('alongX?sx:sx*.22+.025'),'Station side glazing must span its full axis');
assert(door.includes("mount:'jamb'")&&door.includes('mount.add(reader)'),'Readers must be physically parented to jamb mounts');
console.log('PRIVACY + 3F FAST QA PASS');
