import assert from 'node:assert/strict';
import * as THREE from 'three';
import {WorldRouter} from './src/world/WorldRouter.js';

global.document={querySelector:()=>null,createElement:()=>({getContext:()=>new Proxy({},{get:()=>()=>({addColorStop(){}})})})};
const controller={enabled:true,teleport(){},updateCameraRotation(){}};
const router=new WorldRouter(new THREE.Scene(),new THREE.PerspectiveCamera(),controller);
let zone=router.loadZone('first_campus_4f');
const original=zone.colliders.map(box=>[box.min.toArray(),box.max.toArray()]);
const aperture=new THREE.Box3(new THREE.Vector3(13.7,.15,-.35),new THREE.Vector3(14.3,1.95,.35));
assert.equal(zone.wardGateClosed,false,'Ward gate must initially be open');
const insideReader=zone.interactables.find(object=>object.userData.id==='WARD_GATE_ACCESS_INSIDE');
const approach=new THREE.Vector3(15.3,1.7,0),readerPosition=insideReader.getWorldPosition(new THREE.Vector3());
const viewRay=new THREE.Raycaster(approach,readerPosition.clone().sub(approach).normalize(),0,approach.distanceTo(readerPosition)-.1);
assert.equal(viewRay.intersectObjects(zone.wardGatePivot.children,true).length,0,'Open leaf must not hide inside reader from corridor');
assert.equal(zone.colliders.some(box=>box.intersectsBox(aperture)),false);
assert.equal(zone.toggleWardGate(new THREE.Vector3(14,1.7,0)),false,'Must refuse to close into player');
assert.equal(zone.toggleWardGate(new THREE.Vector3(12.7,1.7,0)),true);
assert.equal(zone.wardGateClosed,true);
assert.equal(zone.colliders.length,original.length+1);
assert(zone.colliders.some(box=>box.intersectsBox(aperture)),'Closed gate must block passage');
assert.equal(zone.wardGatePivot.rotation.y,-Math.PI/2,'Visible gate must rotate closed');
zone.setWardGateClosed(true);
assert.equal(zone.colliders.length,original.length+1,'Restoring state must not duplicate gate collider');
for(const [id,x] of [['WARD_GATE_ACCESS',12.7],['WARD_GATE_ACCESS_INSIDE',15.3]]) {
 const reader=zone.interactables.find(object=>object.userData.id===id);
 assert(reader,`Missing reader ${id}`);
 assert.equal(reader.userData.label,'刷卡開啟病房門');
 const origin=new THREE.Vector3(x,1.7,reader.position.z),target=reader.getWorldPosition(new THREE.Vector3());
 const hits=new THREE.Raycaster(origin,target.sub(origin).normalize(),0,2.6).intersectObjects([reader],true);
 assert(hits.length,`Reader must be reachable from ${id}`);
}
router.loadZone('first_campus_3f');
zone=router.loadZone('first_campus_4f');
assert.equal(zone.wardGateClosed,true,'Closed gate state must survive leaving and returning');
assert.equal(zone.toggleWardGate(new THREE.Vector3(15.3,1.7,0)),true,'Inside reader must permit leaving');
assert.equal(zone.wardGateClosed,false);
assert.equal(zone.wardGatePivot.rotation.y,0);
assert.deepEqual(zone.colliders.map(box=>[box.min.toArray(),box.max.toArray()]),original,'Reopening restores original open colliders');
assert.equal(zone.interactables.find(object=>object.userData.id==='WARD_GATE_ACCESS_INSIDE').userData.label,'刷卡關閉病房門');
router.loadZone('first_campus_3f');
zone=router.loadZone('first_campus_4f');
assert.equal(zone.wardGateClosed,false,'Open state must also survive returning');
zone.cleanup();
assert.equal(zone.colliders.length,0);
console.log('WARD GATE PASS: initial open, occupancy guard, visible closed leaf, collision, two readers, closed/open revisit persistence, cleanup');
